### ISSUE TITLE
metronome lambda

### ISSUE THREAD

**Issue by RdeHevia** [monsoon-load-testing/monsoon#33]

**Comment by RdeHevia** [comment]
- [ ] Disable EventBridge rule: arn:aws:events:us-east-1:270778738836:rule/invoke-metronome-lambda-rule
- [x] Test the lambda modifies timestamps.json and save it to S3
- [x] Test timestamps that haven't expired are not removed from the array.

**Comment by alexfdrover** [comment]
See https://github.com/monsoon-load-testing/monsoon/issues/41
