### ISSUE TITLE
Define real intervals for maxRunTime, normalizer.js and metronome lambda

### ISSUE THREAD

**Issue by alexfdrover** [monsoon-load-testing/monsoon#47]

**Comment by RdeHevia** [comment]
- [ ] runner.js: maxRunTime
- [ ] normalizer.js: initialOffset
- [ ] Metronome lambda: expirationTime
maxRunTime < initialOffset << expirationTime
E.g.

maxRunTime = 55s, initialOffset = 60s, expirationTime = 180s
