### ISSUE TITLE
Aggregating lambda: table name should be dynamic

### ISSUE THREAD

**Issue by monsoon-load-testing** [monsoon-load-testing/monsoon#58]

**Comment by monsoon-load-testing** [comment]
Currently all tests are written to the same Timestream table named "test1". Aggregating lambda should:

- [ ] write to a table with a name generated dynamically. For example, the table name could be timeOriginTimestamp
- [ ] If the table doesn't exist in the database, it should create it.

**Comment by RdeHevia** [comment]
Workflow
1. user starts the test.
2. test name is sent to the starting lambda
3. The starting lambda adds the test name to timestamps.json. testName= nameSpecifiedByUser + timeOrigin
4. Metronome sends event to aggregating lambda. the event includes testName as one of the properties.
5. Aggregating lambda receives the event:
    5.1. if the table doesn't exist in the db -> it creates it
    5.2. write data to the specified table.
