### ISSUE TITLE
Normalizer: handle metrics.passed

### ISSUE THREAD

**Issue by RdeHevia** [monsoon-load-testing/monsoon#68]

**Comment by RdeHevia** [comment]
INPUT: metrics: { responseTime: Number || null, passed: boolean }
OUTPUT: metrics: {{normalizedResponseTime: Number, passCount: Number, failCount: Number, transactionRate: Number}, sampleCount: Number }
For each input json file, normalizer should:

If passed === true:
   - use responseTime to calculate normalizedResponseTime
   - passCount += 1
else if passed === false:
   - failCount += 1
in both situations:
   - sampleCount += 1
   - use sampleCount to calculate transactionRate: transactionRate = (sampleCount / 15s) * (60s / 1min)

**Comment by minhphanhvu** [comment]
For transactionRate, we assume you want us to Math.round?
