### ISSUE TITLE
Starting Lambda

### ISSUE THREAD

**Issue by monsoon-load-testing** [monsoon-load-testing/monsoon#7]

**Comment by RdeHevia** [comment]
- [ ] Create EventBridge rule to trigger Metronome Lambda every X minutes.
- [ ] Create originTimestamp (Date.now())
- [ ] Create config.json from test parameters (number of users and test duration) and save in S3 bucket.
- [ ] Create normalizedTimestamps.json and save in S3 bucket.
- [ ] Send start command to ECS
