### ISSUE TITLE
Metronome lambda: remove ECS tasks

### ISSUE THREAD

**Issue by RdeHevia** [monsoon-load-testing/monsoon#76]

**Comment by RdeHevia** [comment]
```javascript
const AWS = require("aws-sdk");
const ecs = new AWS.ECS();

const listTasks = async () => {
  const params = {
    cluster: process.env.clusterName, // Passed from cdk level
  };
  const tasks = await ecs.listTasks(params).promise();
  return tasks.taskArns;
};

const stopTasks = async (taskArns) => {
  for (taskArn of taskArns) {
    const params = {
      task: taskArn,
      cluster: process.env.clusterName,
    };
    await ecs.stopTask(params).promise();
  }
};

(async () => {
  const taskArns = await listTasks();
  await stopTasks(taskArns);
})();
```

**Comment by minhphanhvu** [comment]
Just a small detail. If there are too many containers, the async call can take more than just 3 seconds to kill all containers. You may want to increase the timeout of the metronome lambda in the cdk `timeout: Duration.seconds(10)` to 10s or sth like that.

**Comment by alexfdrover** [comment]
- [x] remove Service functionality
- [x] test existing metronome lambda - should kill ECS Tasks
- [ ] (if needed) add ECSFullPermission to metronome lambda
- [ ] (if needed) test metronome lambda again - should kill ECS Tasks
