### ISSUE TITLE
weather-channel dashboard: add either a refresh button or a enable real time button

### ISSUE THREAD

**Issue by RdeHevia** [monsoon-load-testing/monsoon#80]

**Comment by RdeHevia** [comment]
React router doesn't like refresh page. We should provide that functionality in our site. 2 options:
1) Refresh button. When the user clicks on it, ajax requests are sent to /api/tests/:tableName and /api/tests/:tableName:stats  to get all the test data and data is updated.

2) Enable real time. When this button is activated, ajax are sent to the backend every 3min

**Comment by alexfdrover** [comment]
Moved to https://github.com/monsoon-load-testing/dashboard/issues/2
